//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flyniapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airline
    {
        public Airline()
        {
            this.Flight = new HashSet<Flight>();
        }
    
        public int id_airline { get; set; }
        public string airline_name { get; set; }
        public string address { get; set; }
        public string description { get; set; }
        public string office_phone { get; set; }
        public string office_fax { get; set; }
        public string reservation_phone { get; set; }
        public string reservation_fax { get; set; }
        public string hours_care { get; set; }
        public string airline_url { get; set; }
        public string image_url { get; set; }
    
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
