//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flyniapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_category
    {
        public Flight_category()
        {
            this.Flight_type = new HashSet<Flight_type>();
        }
    
        public int id_category_flight { get; set; }
        public string category_name { get; set; }
    
        public virtual ICollection<Flight_type> Flight_type { get; set; }
    }
}
