//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flyniapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Flight = new HashSet<Flight>();
        }
    
        public int id_status { get; set; }
        public string status_name { get; set; }
    
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
